  channels
  - id: "1281624126250946641"
    name: "QR D"
    duty: "Dragonsong's Reprise (Ultimate)"
    dataCentres: [Aether]
  - id: "1281624147599953971"
    name: "QR TOP"
    duty: "The Omega Protocol (Ultimate)"
    dataCentres: [Aether]
  - id: "1281624175789740083"
    duty: "The Epic of Alexander (Ultimate)"
    dataCentres: [Aether]
  - id: "1281624193703743571"
    name: "QR UWU"
    duty: "The Weapon's Refrain (Ultimate)"
    dataCentres: [Aether]
  - id: "1281624208639787018"
    name: "QR UCOB"
    duty: "The Unending Coil of Bahamut"
    dataCentres: [Aether]
