channels:
  - id: "1281624126250946641"
    name: "dsr"
    duty: "Dragonsong's Reprise (Ultimate)"
    dataCentres: [Aether]
  - id: "1281624147599953971"
    name: "top"
    duty: "The Omega Protocol (Ultimate)"
    dataCentres: [Aether]
  - id: "1281672998646186124"
    name: "tea"
    duty: "The Epic of Alexander (Ultimate)"
    dataCentres: [Aether]
  - id: "1281624193703743571"
    name: "uwu"
    duty: "The Weapon's Refrain (Ultimate)"
    dataCentres: [Aether]
  - id: "1281624208639787018"
    name: "ucob"
    duty: "The Unending Coil of Bahamut (Ultimate)"
    dataCentres: [Aether]
  - id: "1307850313339764827"
    name: "fru"
    duty: "Futures Rewritten (Ultimate)"
    dataCentres: [Aether]
