channels:
  - id: "1281624126250946641"
    name: "dsr"
    duty: "Dragonsong's Reprise (Ultimate)"
    dataCentres: [Aether]
  - id: "1281624147599953971"
    name: "top"
    duty: "The Omega Protocol (Ultimate)"
    dataCentres: [Aether]
  - id: "1281624175789740084"
    name: "tea"
    duty: "The Epic of Alexander (Ultimate)"
    dataCentres: [Aether]
  - id: "1281624193703743571"
    name: "uwu"
    duty: "The Weapon's Refrain (Ultimate)"
    dataCentres: [Aether]
  - id: "1281624208639787018"
    name: "ucob"
    duty: "The Unending Coil of Bahamut (Ultimate)"
    dataCentres: [Aether]
  - id: "1281662003135512586"
    name: "m1s"
    duty: "AAC Light-heavyweight M1 (Savage)"
    dataCentres: [Aether]
  - id: "1281662003135512586"
    name: "m2s"
    duty: "AAC Light-heavyweight M2 (Savage)"
    dataCentres: [Aether]
  - id: "1281662003135512586"
    name: "m3s"
    duty: "AAC Light-heavyweight M3 (Savage)"
    dataCentres: [Aether]
  - id: "1281662003135512586"
    name: "m4s"
    duty: "AAC Light-heavyweight M4 (Savage)"
    dataCentres: [Aether]
